#!/bin/bash

# Get RPI infos
printf "Type in RPI IP address:"
read rpi_address

# Get all commands to be executed on RPI
printf "Get all commands to be executed on RPI...\n"
temp_dir = "/tmp/rpi-configuration"
rm -rf $temp_dir
git clone https://github.com/devgiants/raspberrypi-initialisation-script.git $tmp_dir
commands=$(cat $tmp_dir/script1)
printf "\e[1m\e[32mDONE\e[39m\e[21m\n"

# execute on RPI
printf "Running remote commands...\n"
ssh pi@$rpi_address "$commands"
printf "\e[1m\e[32mDONE RUNNING REMOTE COMMANDS\e[39m\e[21m\n"


echo $hostname
echo $username
# Get public key path to setup SSH connection
#printf "Type in public key path [~/.ssh/id_rsa.pub]:"
#read key_path
#key_path=${key_path:-~/.ssh/id_rsa.pub}

# Copy public key on RPI
#ssh-copy-id -i $key_path 

